// <auto-generated />
using EFCoreTutorials;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Googlekeep.Migrations
{
    [DbContext(typeof(KeepContext))]
    [Migration("20180921063705_KEEPDB12")]
    partial class KEEPDB12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreTutorials.CheckList", b =>
                {
                    b.Property<int>("CheckListId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheckListName")
                        .IsRequired();

                    b.Property<int>("StudentId");

                    b.HasKey("CheckListId");

                    b.HasIndex("StudentId");

                    b.ToTable("Check");
                });

            modelBuilder.Entity("EFCoreTutorials.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LabelName")
                        .IsRequired();

                    b.Property<int>("StudentId");

                    b.HasKey("LabelId");

                    b.HasIndex("StudentId");

                    b.ToTable("Lab");
                });

            modelBuilder.Entity("EFCoreTutorials.Student", b =>
                {
                    b.Property<int>("StudentId");

                    b.Property<string>("PlainText");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<bool>("pinned");

                    b.HasKey("StudentId");

                    b.ToTable("Stu");
                });

            modelBuilder.Entity("EFCoreTutorials.CheckList", b =>
                {
                    b.HasOne("EFCoreTutorials.Student")
                        .WithMany("checkLists")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFCoreTutorials.Label", b =>
                {
                    b.HasOne("EFCoreTutorials.Student")
                        .WithMany("labels")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
